### ISSUE TITLE
Lexical or Preprocessor Issue (Xcode): 'JPush/JPUSHService.h' file not found

### ISSUE THREAD

**Issue by youyiying** [Wayaer/fl_jpush#2]
fl_push.podspec默认没有指定版本,会获取最新版本,新版本的import变了.
s.dependency 'JCore'
s.dependency 'JPush'
解决这个问题需要修改fl_push.podspec指定版本
s.dependency 'JCore','4.2.0'
s.dependency 'JPush','5.0.0'

**Comment by Wayaer** [comment]
已经更新版本，极光sdk更新至最新了
