### ISSUE TITLE
Swift Compiler Error (Xcode): Could not build Objective-C module 'fl_jpush'

### ISSUE THREAD

**Issue by youyiying** [Wayaer/fl_jpush#3]
升级后报错了,不知道是什么原因?

**Comment by Wayaer** [comment]
最低限制12
podfile中添加
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)   
             # 新增
                target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
                end
             # 新增
  end
end
```

**Comment by youyiying** [comment]
`Swift Compiler Error (Xcode): Include of non-modular header inside framework module
'fl_jpush.fl_jpush':
'/flutter_project/build/ios/Release-dev-iphoneos/XCFramew
orkIntermediates/JPush/Headers/JPUSHService.h'
/Users/xxxxx/.pub-cache/hosted/pub.dev/fl_jpush-4.0.1/ios/Classes/fl_jpush.h:0:8
 
 
Swift Compiler Error (Xcode): Could not build Objective-C module 'fl_jpush'
 
 
Encountered error while building for device.`
添加后一样没有报错，这是完整的异常
尝试过添加以下，也是没用
 config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
 config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'

**Comment by Wayaer** [comment]
你项目创建的时候 选择的 Swift ？不是混编的项目吧？

**Comment by youyiying** [comment]
是swift,都是flutter自动生成的ios项目

**Comment by Wayaer** [comment]
![image](https://github.com/Wayaer/fl_jpush/assets/17231965/7b051834-1ef6-49d6-8709-d040b3c0e85d)
我本地老项目 完全可以跑，上次说了后，我测试了新的swift项目也都可以，但是要限制最低12

**Comment by Wayaer** [comment]
你尝试下 
删除 `ios/pods` 目录
`flutter pub get `
`cd ios`
`pod update`

**Comment by youyiying** [comment]
xcode版本问题
