### ISSUE TITLE
applyAuthorityWithIOS问题

### ISSUE THREAD

**Issue by youyiying** [Wayaer/fl_jpush#4]
4.0.1版本第一次打开调用applyAuthorityWithIOS不会没有允许通知的弹窗，切换回3.4.0正常

**Comment by Wayaer** [comment]
![image](https://github.com/Wayaer/fl_jpush/assets/17231965/2bd393b0-e2d1-4f57-af36-99d24804b119)

先这样设置下

**Comment by Wayaer** [comment]
或者更新到4.0.2

**Comment by youyiying** [comment]
又出现新的问题，只有角标更新变化了，没有声音也没有通知横幅。设置通知里面都是勾选的。

**Comment by youyiying** [comment]
我修改极光的版本正常，问题应该出现最新版本
  s.dependency 'JCore','4.2.0'
  s.dependency 'JPush','5.0.0'
